version: '3.8'

services:
  coordinator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://streamr:streamr@db:5432/streamr_poc
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://streamr:streamr@db:5432/streamr_poc
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
    command: ["python", "-m", "app.worker"]
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=streamr
      - POSTGRES_PASSWORD=streamr
      - POSTGRES_DB=streamr_poc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: 